POST  https://ze0hor39xk.execute-api.us-east-1.amazonaws.com/default/certificate_automation 
Content-Type: application/json

{
"thingName": "Device41","delete":true
}

###
GET https://ze0hor39xk.execute-api.us-east-1.amazonaws.com/default/certificate_automation
###
GET https://emvnh9buoh.execute-api.us-east-1.amazonaws.com/getData?device_id=8&start_time=2024-01-01&&;DROP%20TABLE%20users;%20--&end_time=2024-01-02
